# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    twig:
        mode:             lazy
    resolvers:
            default:
                web_path:
                    # web_root: '%kernel.project_dir%/public/uploads'
                    cache_prefix: /uploads/cache
    # default_image: /img/no-picture.jpg
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        mini: 
            quality: 10
            filters: 
                thumbnail:
                    size: [50, 50]
                    mode: outbound
        thumb: 
            quality: 50
            filters: 
                thumbnail:
                    size: [120, 120]
                    mode: outbound
        profile: 
            quality: 50
            filters: 
                thumbnail:
                    size: [400, 400]
                    mode: outbound
        img: 
            quality: 100
            filters: 
                thumbnail:
                    size: [600, 400]
                    mode: outbound
        # carousel:
        #     quality: 100
        #     filters:
        #         thumbnail:
        #             size: [1200, 720]
        #             mode: outbound
           