vich_uploader:
    db_driver: orm

    #mappings:
    #    projects:
    #        uri_prefix: /images/projects
    #        upload_destination: '%kernel.project_dir%/public/images/projects'

    mappings:

        project_images:
            uri_prefix: '%app.path.projectimages%'
            upload_destination: '%kernel.project_dir%/public%app.path.projectimages%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer