monolog:
    channels: ['contact', 'login']
    handlers:
        security:
            # log all messages (since debug is the lowest level)
            level:    error
            type:  rotating_file
            max_files: 30
            path:     '%kernel.logs_dir%/dev/security.log'
            channels: ["security"]
        doctrine:
            # log all messages (since debug is the lowest level)
            level:    error
            type:  rotating_file
            max_files: 30
            path:     '%kernel.logs_dir%/dev/doctrine.log'
            channels: ["doctrine"]
        request:
            # log all messages (since debug is the lowest level)
            level:    critical
            type:  rotating_file
            max_files: 30
            path:     '%kernel.logs_dir%/dev/request.log'
            channels: ["request"]
        login:
            type:  rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/dev/login.log"
            level: debug
            channels: ["login"]
        contact:
            type:  rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/dev/contact.log"
            level: debug
            channels: ["contact"]
        main:
            type:  rotating_file
            max_files: 30
            path: '%kernel.logs_dir%/dev/main.log'
            level: error
            channels: ['!event', '!doctrine', '!security', '!request', '!login', '!contact']
